# Site settings
title: Grace
email: grace@gracez.me
description: Learn more about Grace Z.!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gracez.me" # the base hostname & protocol for your site
twitter_username: gzgracez
github_username:  gzgracez

# Build settings
markdown: kramdown
keep_files: ["css/bootstrap.min.css", "css/one.css"]